spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:11000




server:
  port: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health

currency:
  conversion:
    from: USD
    to: INR
    value: 82
