spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://${config.server.url}


config:
  server:
    host: localhost
    port: 11000
    url: ${config.server.host}:${config.server.port}



server:
  port: 10000

eureka:
  server:
    host: localhost
    port: 12000
    url: ${eureka.server.host}:${eureka.server.port}
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.server.url}/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health

currency:
  conversion:
    from: USD
    to: INR
    value: 82
